### ISSUE TITLE
Doesn’t fill the whole page on a mobile device.- major

### ISSUE THREAD

**Issue by Ghermo35** [info442-su23/f-team#102] opened 2023-08-09 05:48 UTC
![26D8D9A8-2680-4B64-80C9-3E1106BE747D](https://github.com/info442-su23/f-team/assets/43656152/257f189b-42cf-4a5c-b2f5-15d7a69014db)

On my iPhone 14 pro it is very zoomed out but otherwise very functional and great app.

**Comment by EloraHob** [comment] 2023-08-10 03:13
We do not have a requirement indicating our site must be mobile-friendly, therefore I disagree with this being categorized as a major bug.

**Comment by EloraHob** [comment] 2023-08-11 00:05
Duplicate of issue #84

**Closed** 2023-08-11 00:47 UTC
Labels: invalid
